name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: setup .NET 5 
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      
      
      - name: Restore dependencies
        run: dotnet restore
        
      - name: build app
        run: dotnet buld -c Release --no-restore
 
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
